### ISSUE TITLE
Oi gata

### ISSUE THREAD

**Issue by ruangato** [samanthacorrea/teewa-sam#1]
saudades dos seus beijos e carícias <3

**Comment by samanthacorrea** [comment]
saudades xyah <3 <3 <3

**Comment by ruangato** [comment]
E aí, quando vamos pular de para-quedas? kdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdkkdkdkdkdk

**Comment by samanthacorrea** [comment]
eu já to querendo é fazer o curso de paraquedismo
tu pesa mais que 100kg? tem um limite parece

**Comment by ruangato** [comment]
Então já era
